# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "clickworthy-resume"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Abdullah Hendy"]
license = "MIT"
description = "A simple, flexible, responsive, ATS-friendly, and click-worthy resume."
repository = "https://github.com/AbdullahHendy/clickworthy-resume"
keywords = ["cv", "resume"]
categories = ["cv"]
exclude = [
	".github",
	"tests",
    "examples",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
