name: Build-Test CI

on:
  push:
    branches: ["**"]  # Trigger on all branches
  pull_request:
    branches: ["**"]  # Trigger on all PRs

permissions:
  contents: read  # Minimally scoped permissions for GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: ^0.15.1

      - name: Cache Cargo tools
        id: cargo-cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
          key: ${{ runner.os }}-cargo-tytanic-0.4.1-typst-package-check-0.7.0

      - name: Install Cargo tools
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: |
          cargo install --locked --git https://github.com/typst/package-check.git --tag v0.7.0
          cargo install --locked tytanic@0.4.1

      - name: Lint and build project (Install package to local Typst)
        run: |
          make lint
          make install

      - name: Run tests
        run: |
          make test

      - name: Clean up (Uninstall package from local Typst)
        run: |
          make uninstall

      - name: Upload test artifacts (diffs, output, refs)
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: tytanic-artifacts
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5
